[package]
name = "vireon-core"
version = "0.1.0"
edition = "2024"

[dependencies]
secrecy = "0.10.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tracing = "0.1.41"
zeroize = "1.8.1"
